# Generated by Django 4.0.3 on 2022-05-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
