# Generated by Django 4.0.3 on 2022-05-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sample_remove_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
