# Generated by Django 4.0.3 on 2022-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_tag',
            field=models.CharField(choices=[('Django', 'Django'), ('Nodejs', 'Nodejs'), ('Python', 'Python'), ('C#', 'C#'), ('Java', 'Java'), ('C++', 'C++')], max_length=100, null=True),
        ),
    ]
