# Generated by Django 4.0.3 on 2022-05-29 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to=settings.AUTH_USER_MODEL),
        ),
    ]
